[Pliki i foldery]
# Plik bazowy zawierajacy wyeksportowane torowisko (uzywany do offsetu i odleglosci)
TRACK_FILENAMES = scn-wroclaw/EXPORT.SCN, scn-zmigrod/EXPORT.SCN, scn-jawsl/EXPORT.SCN, scn-walbrzych/EXPORT.SCN

# ZMIENIONO: Plik zbiorczy .scn zawierajacy wpisy wczytujace binarne kafelki terenu .e3d
TERRAIN_FILENAME = teren_e3d.scm

# Katalog zawierajacy pliki zrodlowe CityGML (.gml / .xml)
INPUT_DIRS = gmldir-wroclaw, gmldir-zmigrod, gmldir-jawsl, gmldir-walbrzych
#INPUT_DIRS = gmldir-walbrzych

# Nazwa pliku wynikowego dla symulatora (z wygenerowanymi obiektami 3D)
OUTPUT_FILENAME = citygml.scm

[Eksport E3D]
# Wlaczenie zapisu zoptymalizowanych kafelkow do formatu binarnego (.e3d)
EXPORT_E3D = true

# Folder, do ktorego zostana zapisane pliki .e3d (zostanie automatycznie utworzony)
OUTPUT_DIR_E3D = kafle_gml

# Rozmiar pojedynczego kwadratu siatki (kafelka) w metrach. Zalecane: 1000.0 (1 km)
E3D_TILE_SIZE = 1000.0

# Odleglosc rysowania obiektow z tego kafelka w symulatorze (w metrach)
E3D_MAX_DISTANCE = 50000.0


[Geometria]
# Maksymalna odleglosc budynku od najblizszego toru (w metrach).
# Obiekty znajdujace sie dalej niz ta wartosc beda ignorowane.
FILTER_DISTANCE = 2000.0

# Odwracanie osi X i Y w plikach GML (true / false).
# Wymagane dla danych pochodzacych z polskich serwerow mapowych (uklad PUWG 1992).
SWAP_GML_XY = true

# Minimalny dystans miedzy wierzcholkami poligonu w metrach (0.01 = 1 cm).
# Zapobiega bledom w triangulacji i eliminuje zduplikowane wierzcholki.
MIN_VERTEX_DIST = 0.01

# Minimalne pole wygenerowanego trojkata (w metrach kwadratowych).
# Czesci geometrii mniejsze niz ta wartosc beda odrzucane (optymalizacja wydajnosci).
MIN_TRIANGLE_AREA = 0.01


[Tekstury]
# Domyslna tekstura nakladana na dachy budynkow.
TEX_ROOF = roof/karpiowka

# Domyslna tekstura nakladana na sciany budynkow.
TEX_WALL = beton2

# Domyslna tekstura nakladana na podlogi / podstawe budynkow (GroundSurface).
TEX_GROUND = asphaltdark1

# Skala mapowania tekstur. 
# 0.1 oznacza, ze 1 kafelek tekstury przypada na 10 metrow sciany.
# Ustaw na 0.2 lub 0.25 jesli tekstura okien/cegiel wydaje sie zbyt duza.
TEX_SCALE = 0.2
